SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO"; SET time_zone = "+00:00"; CREATE TABLE IF NOT EXISTS `accounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_account_id` int(10) unsigned DEFAULT NULL,
  `account_type_id` tinyint(3) unsigned DEFAULT NULL,
  `reserved` BOOLEAN NOT NULL DEFAULT '0',
  `deposit` tinyint(1) NOT NULL DEFAULT '0',
  `payment` tinyint(1) NOT NULL DEFAULT '0',
  `receivable` tinyint(1) NOT NULL DEFAULT '0',
  `payable` tinyint(1) NOT NULL DEFAULT '0',
  `writeoff` tinyint(1) NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `reconcilable` tinyint(1) NOT NULL DEFAULT '0',
  `terms` tinyint(3) unsigned DEFAULT NULL,
  `balance` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `account_reconciles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(10) unsigned DEFAULT NULL,
  `date` date DEFAULT NULL,
  `balance_start` decimal(15,2) DEFAULT NULL,
  `balance_end` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `account_transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `transaction_id` bigint(20) unsigned DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `date` date DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `balance` decimal(15,2) DEFAULT NULL,
  `account_reconcile_id` bigint(20) unsigned DEFAULT NULL,
  `transfer` BOOLEAN NOT NULL DEFAULT '0',
  `writeoff` BOOLEAN NOT NULL DEFAULT '0',
  `close_books` BOOLEAN NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `account_transaction_forms` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_transaction_id` bigint(20) unsigned DEFAULT NULL,
  `form_id` bigint(20) unsigned DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `writeoff_amount` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `account_types` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `table_sign` tinyint(1) NOT NULL DEFAULT '0',
  `deposit` tinyint(1) NOT NULL DEFAULT '0',
  `payment` tinyint(1) NOT NULL DEFAULT '0',
  `receivable` tinyint(1) NOT NULL DEFAULT '0',
  `payable` tinyint(1) NOT NULL DEFAULT '0',
  `reconcilable` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `entities` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `default_shipping_address_id` bigint(20) unsigned DEFAULT NULL,
  `default_billing_address_id` bigint(20) unsigned DEFAULT NULL,
  `default_remit_address_id` bigint(20) unsigned DEFAULT NULL,
  `default_account_id` int(10) unsigned DEFAULT NULL,
  `type` enum('customer','vendor') DEFAULT NULL,
  `first_name` varchar(64) DEFAULT NULL,
  `last_name` varchar(64) DEFAULT NULL,
  `company_name` varchar(64) DEFAULT NULL,
  `email` varchar(256) DEFAULT NULL,
  `phone_number` varchar(32) DEFAULT NULL,
  `fax_number` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `entity_addresses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` bigint(20) unsigned DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `zip` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `forms` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` bigint(20) unsigned DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `create_transaction_id` bigint(20) unsigned DEFAULT NULL,
  `invoice_transaction_id` bigint(20) unsigned DEFAULT NULL,
  `cancel_transaction_id` bigint(20) unsigned DEFAULT NULL,
  `refund_form_id` bigint(20) unsigned DEFAULT NULL,
  `shipping_address_id` bigint(20) unsigned DEFAULT NULL,
  `billing_address_id` bigint(20) unsigned DEFAULT NULL,
  `remit_address_id` bigint(20) unsigned DEFAULT NULL,
  `type` enum('sale','expense','purchase') DEFAULT NULL,
  `sent` enum('print','email','both') DEFAULT NULL,
  `date_created` date DEFAULT NULL,
  `date_billed` date DEFAULT NULL,
  `date_due` date DEFAULT NULL,
  `date_cancelled` date DEFAULT NULL,
  `code` varchar(16) DEFAULT NULL,
  `reference` varchar(16) DEFAULT NULL,
  `alt_reference` varchar(16) DEFAULT NULL,
  `aux_reference` varchar(16) DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `total` decimal(15,2) DEFAULT NULL,
  `balance` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000 ; CREATE TABLE IF NOT EXISTS `form_lines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` bigint(20) unsigned DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `adjustment` BOOLEAN NOT NULL DEFAULT '0',
  `description` varchar(128) DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `quantity` int(10) unsigned DEFAULT NULL,
  `total` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `form_line_taxes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_line_id` bigint(20) unsigned DEFAULT NULL,
  `tax_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `form_taxes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` bigint(20) unsigned DEFAULT NULL,
  `tax_id` bigint(20) unsigned DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `percent` decimal(6,6) DEFAULT NULL,
  `fee` decimal(10,2) DEFAULT NULL,
  `total` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `timestamp` bigint(20) unsigned DEFAULT NULL,
  `object_id` bigint(20) unsigned DEFAULT NULL,
  `data` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) DEFAULT NULL,
  `code` varchar(16) DEFAULT NULL,
  `description` text,
  `user_limit` int(10) unsigned DEFAULT NULL,
  `auth_expiration_length` bigint(20) DEFAULT NULL,
  `customer_read` tinyint(1) NOT NULL DEFAULT '0',
  `customer_write` tinyint(1) NOT NULL DEFAULT '0',
  `customer_sale_read` tinyint(1) NOT NULL DEFAULT '0',
  `customer_sale_write` tinyint(1) NOT NULL DEFAULT '0',
  `customer_payment_read` tinyint(1) NOT NULL DEFAULT '0',
  `customer_payment_write` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_read` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_write` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_expense_read` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_expense_write` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_purchase_read` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_purchase_write` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_payment_read` tinyint(1) NOT NULL DEFAULT '0',
  `vendor_payment_write` tinyint(1) NOT NULL DEFAULT '0',
  `account_read` tinyint(1) NOT NULL DEFAULT '0',
  `account_write` tinyint(1) NOT NULL DEFAULT '0',
  `account_transaction_read` tinyint(1) NOT NULL DEFAULT '0',
  `account_transaction_write` tinyint(1) NOT NULL DEFAULT '0',
  `account_reconcile` tinyint(1) NOT NULL DEFAULT '0',
  `books` tinyint(1) NOT NULL DEFAULT '0',
  `reports` tinyint(1) NOT NULL DEFAULT '0',
  `setup` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(64) DEFAULT NULL,
  `value` text,
  `reserved` BOOLEAN NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `taxes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `code` varchar(16) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `percent` decimal(6,6) DEFAULT NULL,
  `fee` decimal(10,2) DEFAULT NULL,
  `total` decimal(15,2) DEFAULT NULL,
  `balance` decimal(15,2) DEFAULT NULL,
  `date_due` DATE DEFAULT NULL,
  `date_due_months_increment` TINYINT UNSIGNED DEFAULT NULL, 
  `license` VARCHAR( 255 ) DEFAULT NULL,
  `authority` VARCHAR( 255 ) DEFAULT NULL,
  `address1` VARCHAR( 255 ) DEFAULT NULL,
  `address2` VARCHAR( 255 ) DEFAULT NULL,
  `city` VARCHAR( 255 ) DEFAULT NULL,
  `state` VARCHAR( 255 ) DEFAULT NULL,
  `zip` VARCHAR( 255 ) DEFAULT NULL,
  `country` VARCHAR( 255 ) DEFAULT NULL, 
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `tax_payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tax_id` bigint(20) unsigned DEFAULT NULL,
  `date` date DEFAULT NULL,
  `date_start` date DEFAULT NULL,
  `date_end` date DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `transaction_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entity_id` bigint(20) unsigned DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `reference` varchar(16) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `payment` enum('customer','vendor','expense') DEFAULT NULL,
  `close_books` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ; CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) DEFAULT NULL,
  `email` varchar(256) DEFAULT NULL,
  `reset` varchar(128) DEFAULT NULL,
  `reset_expiration` bigint(20) unsigned DEFAULT NULL,
  `password_change`tinyint(1) NOT NULL DEFAULT '0',
  `password` varchar(128) DEFAULT NULL,
  `role_id` int(10) unsigned DEFAULT NULL,
  `auth_expiration` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;